-- MySQL Script generated by MySQL Workbench
-- Sa 30 Mai 2020 22:36:19 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ITSecDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ITSecDB` ;

-- -----------------------------------------------------
-- Schema ITSecDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ITSecDB` DEFAULT CHARACTER SET utf8 ;
USE `ITSecDB` ;

-- -----------------------------------------------------
-- Table `ITSecDB`.`blogentry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITSecDB`.`blogentry` ;

CREATE TABLE IF NOT EXISTS `ITSecDB`.`blogentry` (
  `idblogentry` INT AUTO_INCREMENT,
  `blogtext` VARCHAR(256) NULL,
  `bloguser_idbloguser` INT NULL,
  PRIMARY KEY (`idblogentry`),
  INDEX `fk_blogentry_bloguser_idx` (`bloguser_idbloguser` ASC) VISIBLE,
  CONSTRAINT `fk_blogentry_bloguser`
    FOREIGN KEY (`bloguser_idbloguser`)
    REFERENCES `ITSecDB`.`bloguser` (`idbloguser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ITSecDB`.`bloguser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITSecDB`.`bloguser` ;

CREATE TABLE IF NOT EXISTS `ITSecDB`.`bloguser` (
  `idbloguser` INT AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `isAdmin` TINYINT NULL,
  PRIMARY KEY (`idbloguser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
